(function(){
'use strict';
const DM=window.Diplomaker=window.Diplomaker||{},U=DM.Utils,TL=DM.TemplateLibrary;
const BASE_WIDTH=1120,BASE_HEIGHT=792,imageCache=new Map();
function loadImage(src){if(imageCache.has(src))return imageCache.get(src);const p=new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error(`No se pudo cargar el recurso ${src}`));img.src=src;});imageCache.set(src,p);return p;}
function setFont(ctx,{size,family='Arial',weight=400,style='normal'}){ctx.font=`${style} ${weight} ${size}px ${family}`;}
function drawCenteredFit(ctx,text,cx,y,maxWidth,font){const value=String(text||'').trim();let size=font.size;setFont(ctx,{...font,size});while(ctx.measureText(value).width>maxWidth&&size>(font.minSize||12)){size--;setFont(ctx,{...font,size});}ctx.fillStyle=font.color||'#111';ctx.textAlign='center';ctx.textBaseline='top';ctx.fillText(value,cx,y);ctx.textAlign='start';return{fontSize:size,shrunk:size<font.size*.8};}
function textWidthWithSpacing(ctx,text,spacing){const chars=[...String(text)];return chars.reduce((n,c)=>n+ctx.measureText(c).width,0)+Math.max(0,chars.length-1)*spacing;}
function drawLetterSpacedCentered(ctx,text,cx,y,spacing,maxWidth,font){const value=String(text||'');let size=font.size;setFont(ctx,{...font,size});let width=textWidthWithSpacing(ctx,value,spacing);while(width>maxWidth&&size>(font.minSize||16)){size--;setFont(ctx,{...font,size});width=textWidthWithSpacing(ctx,value,spacing*size/font.size);}const actual=spacing*size/font.size;let x=cx-width/2;ctx.fillStyle=font.color||'#111';ctx.textBaseline='top';for(const c of [...value]){ctx.fillText(c,x,y);x+=ctx.measureText(c).width+actual;}return{fontSize:size,shrunk:size<font.size*.82};}
function wrapLines(ctx,text,maxWidth,maxLines=Infinity){const lines=[];for(const paragraph of String(text||'').split(/\n+/)){const words=paragraph.split(/\s+/).filter(Boolean);if(!words.length){lines.push('');continue;}let line=words.shift();for(const word of words){const test=`${line} ${word}`;if(ctx.measureText(test).width<=maxWidth)line=test;else{lines.push(line);line=word;}if(lines.length>=maxLines)break;}if(lines.length<maxLines)lines.push(line);if(lines.length>=maxLines)break;}return lines.slice(0,maxLines);}
function drawWrappedCentered(ctx,text,cx,y,maxWidth,opt){let size=opt.size,lines=[];const min=opt.minSize||10,maxLines=opt.maxLines||4;do{setFont(ctx,{...opt,size});lines=wrapLines(ctx,text,maxWidth,maxLines+1);if(lines.length<=maxLines)break;size--;}while(size>=min);const clipped=lines.length>maxLines;lines=lines.slice(0,maxLines);const lh=size*(opt.lineHeight||1.25);ctx.fillStyle=opt.color||'#111';ctx.textAlign='center';ctx.textBaseline='top';lines.forEach((line,i)=>ctx.fillText(line,cx,y+i*lh));ctx.textAlign='start';return{fontSize:size,lines,clipped,height:lines.length*lh,shrunk:size<opt.size*.8};}
function drawRule(ctx,x1,x2,y,color='rgba(0,0,0,.26)'){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(x1,y);ctx.lineTo(x2,y);ctx.stroke();ctx.restore();}
function activeSigners(record,max=12){return(Array.isArray(record.signers)?record.signers:[]).filter(s=>U.normalizeText(s.name)||U.normalizeText(s.role)).slice(0,max);}
function drawSigners(ctx,signers,area,diagnostics){if(!signers.length)return;const columns=signers.length===1?1:2,rows=Math.ceil(signers.length/columns),gapX=38,gapY=12,effective=signers.length===1?Math.min(area.width,500):area.width,origin=area.x+(area.width-effective)/2,cellW=(effective-gapX*(columns-1))/columns,cellH=(area.height-gapY*(rows-1))/rows;signers.forEach((s,i)=>{const row=Math.floor(i/columns),col=i%columns,x=origin+col*(cellW+gapX),y=area.y+row*(cellH+gapY),cx=x+cellW/2;drawRule(ctx,x+12,x+cellW-12,y+8,area.lineColor);const nr=drawCenteredFit(ctx,s.name||'',cx,y+17,cellW-20,{size:18,minSize:11,family:'Arial',weight:700,color:area.color});const rr=drawWrappedCentered(ctx,String(s.role||'').toLocaleUpperCase('es-AR'),cx,y+43,cellW-24,{size:10.2,minSize:8,maxLines:3,lineHeight:1.13,family:'Arial',weight:500,color:area.color});if(nr.shrunk)diagnostics.push({level:'warning',message:`El nombre del firmante “${s.name}” debió reducirse.`});if(rr.shrunk||rr.clipped)diagnostics.push({level:'warning',message:`El cargo de “${s.name||'un firmante'}” es extenso.`});});}
function buildBody(record,template){const type=String(record.certificateType||template.defaultType||'ASISTENCIA').toLocaleLowerCase('es-AR'),event=U.normalizeText(record.eventTitle),date=U.formatDate(record.eventDate);if(record.eventText&&record.eventText!==template.defaultEventText){let custom=U.normalizeText(record.eventText);if(event&&!custom.toLocaleLowerCase('es-AR').includes(event.toLocaleLowerCase('es-AR')))custom+=` ${event}`;if(date&&!custom.includes(date))custom+=` — ${date}`;return custom;}const roleTypes=['panelista','disertante','docente','moderador','moderadora'];const lead=roleTypes.includes(type)?`En reconocimiento por su participación en calidad de ${type}`:`En reconocimiento por su ${type}`;return`${lead}${event?` en “${event}”`:''}${date&&!event.includes(date)?`, realizada el ${date}`:''}.`;}
async function drawBackground(ctx,template){ctx.drawImage(await loadImage(template.background),0,0,BASE_WIDTH,BASE_HEIGHT);}
async function renderLayout(ctx,record,template,diagnostics){const cx=BASE_WIDTH/2,type=String(record.certificateType||template.defaultType).toLocaleUpperCase('es-AR'),name=[record.treatment,record.participantName].filter(Boolean).join(' ');let cfg;if(template.id==='modern')cfg={title:'CERTIFICADO',titleY:132,titleSize:57,titleColor:'#20242a',typeY:197,typeColor:'#8f2d3d',nameY:310,nameColor:'#111',bodyY:412,bodyColor:'#25282c',signY:585,signColor:'#303238',line:'rgba(143,45,61,.33)',upper:true,typePrefix:'DE '};else if(template.id==='academic')cfg={title:'DIPLOMA',titleY:110,titleSize:45,titleColor:'#275d50',typeY:171,typeColor:'#9b722a',nameY:292,nameColor:'#1d463d',bodyY:394,bodyColor:'#35483f',signY:575,signColor:'#27483f',line:'rgba(39,93,80,.30)',upper:false,typePrefix:''};else cfg={title:'CERTIFICADO',titleY:132,titleSize:47,titleColor:'#17365d',typeY:188,typeColor:'#9b762f',nameY:303,nameColor:'#1e2d42',bodyY:405,bodyColor:'#364152',signY:585,signColor:'#24364f',line:'rgba(23,54,93,.30)',upper:false,typePrefix:''};drawCenteredFit(ctx,cfg.title,cx,cfg.titleY,790,{size:cfg.titleSize,minSize:34,family:template.id==='modern'?'Arial':'Georgia',weight:700,color:cfg.titleColor});const tr=drawLetterSpacedCentered(ctx,`${cfg.typePrefix}${type}`,cx,cfg.typeY,template.id==='modern'?4:10,790,{size:template.id==='modern'?28:24,minSize:15,family:'Arial',weight:700,color:cfg.typeColor});if(tr.shrunk)diagnostics.push({level:'warning',message:'El tipo de certificado debió reducirse.'});drawCenteredFit(ctx,template.id==='academic'?'Se reconoce a:':'Se otorga a:',cx,template.id==='academic'?248:259,500,{size:17,minSize:13,family:'Georgia',style:'italic',weight:400,color:'#4c5664'});const nr=drawCenteredFit(ctx,cfg.upper?name.toLocaleUpperCase('es-AR'):name,cx,cfg.nameY,830,{size:template.id==='modern'?53:49,minSize:24,family:'Georgia',weight:700,color:cfg.nameColor});if(nr.shrunk)diagnostics.push({level:'warning',message:'El nombre del participante debió reducirse.'});const br=drawWrappedCentered(ctx,buildBody(record,template),cx,cfg.bodyY,750,{size:17,minSize:12,maxLines:4,lineHeight:1.38,family:template.id==='academic'?'Georgia':'Arial',weight:400,color:cfg.bodyColor});if(br.shrunk||br.clipped)diagnostics.push({level:'warning',message:'El texto del certificado es demasiado extenso.'});drawSigners(ctx,activeSigners(record,4),{x:190,y:cfg.signY,width:740,height:132,color:cfg.signColor,lineColor:cfg.line},diagnostics);}
function baseValidation(record){const m=[];if(!U.normalizeText(record.participantName))m.push({level:'error',message:'Falta el nombre del participante.'});if(!U.normalizeText(record.eventTitle))m.push({level:'warning',message:'No se indicó el evento o actividad.'});if(!U.normalizeText(record.certificateType))m.push({level:'warning',message:'No se indicó el tipo de certificado.'});if(!activeSigners(record).length)m.push({level:'warning',message:'El certificado no tiene firmantes cargados.'});return m;}
function statusFromMessages(m){return m.some(x=>x.level==='error')?'error':m.some(x=>x.level==='warning')?'warning':'ready';}
async function renderCertificate(record,canvas,options={}){const scale=options.scale||1;canvas.width=Math.round(BASE_WIDTH*scale);canvas.height=Math.round(BASE_HEIGHT*scale);const ctx=canvas.getContext('2d',{alpha:false});ctx.save();ctx.scale(scale,scale);ctx.fillStyle='#fff';ctx.fillRect(0,0,BASE_WIDTH,BASE_HEIGHT);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';const template=TL.getTemplate(record.templateId),diagnostics=baseValidation(record);try{await drawBackground(ctx,template);await renderLayout(ctx,record,template,diagnostics);}catch(error){diagnostics.push({level:'error',message:error.message||'No se pudo componer el certificado.'});}ctx.restore();return{status:statusFromMessages(diagnostics),messages:diagnostics,template};}
async function renderToCanvas(record,scale=2){const canvas=document.createElement('canvas'),validation=await renderCertificate(record,canvas,{scale});return{canvas,validation};}
DM.Renderer={BASE_WIDTH,BASE_HEIGHT,renderCertificate,renderToCanvas,loadImage,statusFromMessages,baseValidation};
})();
